apps/front/models.py
from ext import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    phone = db.Column(db.String(11), nullable=False)
    email = db.Column(db.String(50), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    books = db.relationship('Book', backref=db.backref('users'), lazy='dynamic')

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        return check_password_hash(self.password, raw_password)


class Book(db.Model):
    __tablename__ = 'book'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    book_name = db.Column(db.String(255), nullable=False)
    book_author = db.Column(db.String(255))
    book_category = db.Column(db.String(255))
    is_paper = db.Column(db.Boolean, default=1)
    publisher = db.Column(db.String(255))
    price = db.Column(db.Float())
    actual_price = db.Column(db.Float())
    receive_time = db.Column(db.DateTime)
    begin_read_time = db.Column(db.DateTime)
    finish_read_time = db.Column(db.DateTime)
    author_profile = db.Column(db.Text)
    book_profile = db.Column(db.Text)
    reading_notes = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

apps/front/forms.py
from wtforms import Form, StringField, PasswordField
from  wtforms.validators import InputRequired, Length, Email, DataRequired, EqualTo


class LoginForm(Form):
    """
    登录验证表单
    """
    username = StringField(validators=[InputRequired(message='请输入用户名')])
    password = StringField(validators=[InputRequired(message='请输入密码'), Length(6, 20, message='密码长度不对')])
    remember = StringField()


class RegistrationForm(Form):
    """
    注册验证表单
    """
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    confirm = PasswordField('confirm', validators=[DataRequired(), EqualTo('password', message='密码必须保持一致')])
    email = StringField('email', validators=[DataRequired(), Email()])
    phone = StringField('phone', validators=[DataRequired(), Length(min=11, max=11)])

apps/backend/__init__.py
#!usr/bin/env python  
# -*- coding:utf-8 -*-  
# @author: Johnathon Qiang
# @file  : __init__.py.py 
# @time  : 2017/11/24 19:54:04
# @description：

apps/common/__init__.py
#!usr/bin/env python  
# -*- coding:utf-8 -*-  
# @author: Johnathon Qiang
# @file  : __init__.py.py 
# @time  : 2017/11/24 19:53:52
# @description：

apps/front/__init__.py
from .views import bp
import apps.front.models
# import apps.front.hooks
# from .hooks import *

apps/front/views.py
#!usr/bin/env python  
# -*- coding:utf-8 -*-  
# @author: Johnathon Qiang
# @file  : views.py
# @time  : 2017/11/24 19:57:14
# @description：

from flask import (
    Blueprint, views, render_template, redirect, url_for, request, session, flash, g)
from .forms import LoginForm
from .models import User, Book
from config import DevConfig
from ext import db
import random

bp = Blueprint('front', __name__)


@bp.route('/')
def index():
    return render_template('front/index.html')


class LoginView(views.MethodView):
    def get(self):
        return render_template('front/login.html')

    def post(self):
        form = LoginForm(request.form)

        if form.validate():
            username = form.username.data
            password = form.password.data
            remember = form.remember.data

            user = User.query.filter_by(username=username).first()
            if user and user.check_password(password):
                session[DevConfig.USER_ID] = user.id
                if remember:
                    session.permanent = True
                return redirect(url_for('front.index'))
            else:
                flash('用户名或密码有误', 'errors')
                return self.get()
        else:
            # message = form.errors.popitem()[1][0]
            return self.get()


bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))


@bp.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        user = User()
        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')
        phone = request.form.get('phone')
        user.username = username
        user.password = password
        user.email = email
        user.phone = phone
        if user.username and user.password:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('front.login'))
        else:
            flash('用户名和密码不能为空', 'error')
            return render_template('front/register.html')
    return render_template('front/register.html')


@bp.route('/logout/')
def logout():
    del session[DevConfig.USER_ID]
    return redirect(url_for('front.login'))


@bp.route('/list/')
def list_book():
    # 已登录用，查看所有属于自己的记录
    books = Book.query.filter(Book.user_id == session.get('user_id')).all()

    # 未登录用户随机查看十条记录
    book_random = random.sample(Book.query.all(), 5)
    return render_template('front/list_books.html', books=books, book_random=book_random)


@bp.route('/add/', methods=['GET', 'POST'])
def add_book():
    if request.method == 'POST':
        # print(session.get('user_id'))
        book = Book()
        book.book_name = request.form.get('book_name')
        book.book_author = request.form.get('book_author')
        book.publisher = request.form.get('publisher')
        book.book_category = request.form.get('book_category')
        book.is_paper = request.form.get('is_paper')
        # book.price = request.form.get('price')
        # book.actual_price = request.form.get('actual_price')
        # book.receive_time = request.form.get('receive_time')
        # book.begin_read_time = request.form.get('begin_read_time')
        # book.finish_read_time = request.form.get('finish_read_time')
        book.author_profile = request.form.get('author_profile')
        book.book_profile = request.form.get('book_profile')
        book.reading_notes = request.form.get('reading_notes')
        book.user_id = User.query.filter(User.id == session.get('user_id')).first().id
        db.session.add(book)
        db.session.commit()
        return redirect(url_for('front.list_book'))

    return render_template('front/add_books.html')


@bp.before_request
def my_before_request():
    # user_id = session.get(DevConfig.USER_ID)
    # if user_id:
    #     user = User.query.filter(User.id == user_id).first()
    #     if user:
    #         g.user = user
    if DevConfig.USER_ID in session:
        user_id = session.get(DevConfig.USER_ID)
        user = User.query.get(user_id)
        if user:
            g.user = user


@bp.context_processor
def my_context_processor():
    if hasattr(g, 'user'):
        return {'user': g.user}
    return {}

main.py
from flask import Flask
from config import DevConfig
from ext import db
from apps.front import bp as front_bp

# import apps.front.hooks

app = Flask(__name__)
app.config.from_object(DevConfig)
db.init_app(app)

app.register_blueprint(front_bp)

if __name__ == '__main__':
    app.run()

templates/front/_macros.html
{% macro static(filename) %}
    {{ url_for('static', filename=filename) }}
{% endmacro %}

templates/front/add_books.html
{% extends 'front/base.html' %}
{% block title %}
    添加图书信息
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/add.css') }}">
{% endblock %}
{% block body %}
    <form action="{{ url_for('front.add_book') }}" method="post">
        <div class="columns">
            <div class="column is-8 is-offset-2">
                <div class="add-body">
                    <p class="add-title">图书录入</p>

                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label">书名</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <input name="book_name" class="input is-primary" type="text" placeholder="请输入书名">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">作者</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control ">
                                    <input name="book_author" class="input is-primary" type="text" placeholder="请输入作者">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">出版社</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control ">
                                    <input name="publisher" class="input is-primary" type="text" placeholder="请输入出版社">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">图书分类</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control ">
                                    <input name="book_category" class="input is-primary" type="text" placeholder="请输入分类建议">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">书籍载体</label>
                        </div>
                        <div class="field-body">
                            <div class="field ">
                                <div class="control">
                                    <div class="select is-fullwidth is-primary">
                                        <select name="is_paper">
                                            <option>请选择</option>
                                            <option>纸质书</option>
                                            <option>电子书</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">定价</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control ">
                                    <input name="price" class="input is-primary" type="text" placeholder="请输入书籍定价">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">购入价</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control ">
                                    <input name="actual_price" class="input is-primary" type="text" placeholder="请输入买入价格">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">到手日期</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control ">
                                    <input name="receive_time" class="input is-primary" type="text" placeholder="请输入拿到书的日期">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">开始阅读</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control ">
                                    <input name="begin_read_time" class="input is-primary" type="text" placeholder="请输入开始阅读日期">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field  is-horizontal">
                        <div class="field-label">
                            <label class="label">结束阅读</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control ">
                                    <input name="finish_read_time" class="input is-primary" type="text" placeholder="请输入完成阅读日期">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label for="haha" class="label">作者简介</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <textarea name="author_profile" class="textarea is-primary" placeholder="为作者添加一些简介吧..."></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label for="haha" class="label">图书简介</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <textarea name="book_profile" class="textarea is-primary" placeholder="简单介绍一下这本书吧..."></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label is-normal">
                            <label class="label">读后感想</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <textarea name="reading_notes" rows="10" class="textarea is-primary"
                                              placeholder="读完了，记录一下感想吧..."></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <!-- Left empty for spacing -->
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <button class="button is-primary" type="submit">
                                        保存
                                    </button>
                                    <a class="button is-light" type="submit" href="{{ url_for('front.list_book') }}">
                                        取消
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/front/base.html
{% from 'front/_macros.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-人生记录仪</title>
    <link rel="stylesheet" href="{{ static('css/bulma-0.6.0/css/bulma.css') }}">
    <link rel="stylesheet" href="{{ static('css/font-awesome-4.7.0/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ static('css/base.css') }}">
    {% block head %}{% endblock %}
</head>
<body>

<section class="hero is-light is-fullheight">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head is-primary" style="background-color: #fff">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item">
                        {# <img src="https://bulma.io/images/bulma-type-white.png" alt="Logo">#}
                        我是Logo
                    </a>
                    <span class="navbar-burger burger" data-target="navbarMenuHeroC">
            <span></span>
            <span></span>
            <span></span>
          </span>
                </div>
                <div id="navbarMenuHeroC" class="navbar-menu">
                    <div class="navbar-end">
                        <a class="navbar-item" href="{{ url_for('front.index') }}">
                            首页
                        </a>
                        <a class="navbar-item" href="{{ url_for('front.list_book') }}">
                            阅读
                        </a>
                        <a class="navbar-item">
                            影视
                        </a>
                        <a class="navbar-item" href="http://xuanxiewu.com" target="_blank">
                            博客
                        </a>
                        <span class="navbar-item">
                            {% if user %}
                                <a class="button is-primary is-inverted" href="#">
                                <span class="icon">
                                  <i class="fa fa-user"></i>
                                </span>
                                <span>{{ user.username }}</span>
                              </a>&nbsp;
                                <a class="button is-primary is-inverted" href="{{ url_for('front.logout') }}">
                                <span class="icon">
                                  <i class="fa fa-sign-out"></i>
                                </span>
                                <span>注销</span>
                              </a>
                            {% else %}
                                <a class="button is-primary is-inverted" href="{{ url_for('front.login') }}">
                                <span class="icon">
                                  <i class="fa fa-info"></i>
                                </span>
                                <span>登录</span>
                              </a>&nbsp;
                                <a class="button is-primary is-inverted" href="{{ url_for('front.register') }}">
                                <span class="icon">
                                  <i class="fa fa-sign-in"></i>
                                </span>
                                <span>注册</span>
                              </a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </header>
    </div>
    {#    <hr>#}
    <!-- Hero content: will be in the middle -->
    <div class="hero-body">
        <div class="container has-text-centered">
            {% block body %}{% endblock %}
        </div>
    </div>

    <!-- Hero footer: will stick at the bottom -->
    <div class="hero-foot">
        <nav class="tabs is-boxed is-fullwidth">
            <div class="container">
                <div class="clumns">
                    <div class="column is-6 is-offset-3">
                        <div class="has-text-centered">
                            <p class="footer-copyright">@copyright 2017 saltfish.cn | All rights rserved</p>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</section>


</body>
</html>

templates/front/index.html
{% extends 'front/base.html' %}
{% from 'front/_macros.html' import static %}
{% block title %}首页{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ static('css/index.css') }}">
{% endblock %}

{% block body %}
    <form action="" method="post">
        <div class="columns">
            <div class="column is-6 is-offset-3">
                <div class="has-text-centered">
                    <p class="control">
                        <input style="border-radius: 25px" class="input is-primary is-large "
                               placeholder="请输入你要搜索的关键词...">
                    </p>
                    <br>
                    <button type="submit" class="button is-primary is-medium lib-btn" style="border-radius: 25px">搜索图书
                    </button>
                    <button type="submit" class="button is-primary is-medium mv-btn" style="border-radius: 25px">搜索电影
                    </button>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

templates/front/list_books.html
{% extends 'front/base.html' %}
{% block title %}
    图书信息
{% endblock %}

{% block body %}

    {% if user %}
        {% if books %}
            {% for book in books %}
                <p>{{ book.book_name }}</p>
            {% endfor %}
            <p>继续<a style="color: #00b89c" href="{{ url_for('front.add_book') }}">添加图书</a></p>
        {% else %}
            {{ user.username }}还没有添加过图书，请先 <a style="color: #00b89c" href="{{ url_for('front.add_book') }} ">添加图书</a>
        {% endif %}
    {% else %}
        {% if books %}
            {% for book in book_random %}
                <p>{{ book.book_name }}</p>
            {% endfor %}
            <a style="color: #00b89c" href="{{ url_for('front.login') }}">登录</a>查看更多图书资源
        {% else %}
            系统中还没有一本书,赶紧<a style="color: #00b89c" href="{{ url_for('front.login') }}">登录</a>添加图书吧
        {% endif %}
    {% endif %}


{% endblock %}

templates/front/login.html
{% extends 'front/base.html' %}
{% from 'front/_macros.html' import static %}

{% block title %}
    登录
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('css/login.css') }}">
{% endblock %}

{% block body %}
    <form action="{{ url_for('front.login') }}" method="POST">
        <div class="columns">
            <div class="column is-4 is-offset-4">
                <div class="has-text-centered">
                    <div class="login-body">
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="text" name="username" placeholder="请输入用户名">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-user"></i>
                                </span>
                            </p>
                        </div>
                        <br>
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="password" name="password" placeholder="请输入密码">
                                <span class="icon is-small is-left">
                                <i class="fa fa-lock"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <label class="checkbox">
                                <input type="checkbox" name="remember" value="1">
                                记住我
                            </label>
                        </div>
                        {% if not username and not password %}
                            <p style="color: red ;margin-bottom: 10px">{{ get_flashed_messages()[0] }}</p>
                        {% else %}
                            <p style="color: red ;margin-bottom: 10px">{{ get_flashed_messages()[1] }}</p>
                        {% endif %}

                        <input class="button is-primary  is-medium" type="submit" value="登录">
                        <p class="go-register">没有账号？
                            <a style="color: #00b89c;" href="{{ url_for('front.register') }}">立即注册&nbsp;
                                <i class="fa fa-long-arrow-right"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
{#        {% for message in get_flashed_messages() %}#}
{#            <p style="color: red ;margin-bottom: 10px">{{ message }}</p>#}
{#        {% endfor %}#}
    </form>
{% endblock %}

templates/front/register.html
{% extends 'front/base.html' %}

{% block title %}
    注册
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
{% endblock %}

{% block body %}
    <form action="{{ url_for('front.register') }}" method="post">
{#    {{ form.csrf_token }}#}
        <div class="columns">
            <div class="column is-4 is-offset-4">
                <div class="has-text-centered">
                    <div class="login-body">
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="text" name="username" placeholder="请输入用户名">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-user"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="password" name="password" placeholder="请输入密码">
                                <span class="icon is-small is-left">
                                <i class="fa fa-lock"></i>
                                </span>
                            </p>
                        </div>

                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="password" name="confirm" placeholder="请确认密码">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-lock"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control has-icons-left has-icons-right">
                                <input class="input is-primary" type="email" name="email" placeholder="请输入邮箱地址">
                                <span class="icon is-small is-left">
                                    <i class="fa fa-envelope"></i>
                                </span>
                                <span class="icon is-small is-right">
                                    <i class="fa fa-check"></i>
                                </span>
                            </p>
                        </div>
                        <div class="field">
                            <p class="control has-icons-left">
                                <input class="input is-primary" type="tel" name="phone" placeholder="请输入手机号码">
                                <span class="icon is-small is-left">
                                <i class="fa fa-phone"></i>
                                </span>
                            </p>
                        </div>
                        <br>
                        {% for message in get_flashed_messages() %}
                            <p style="color: red ;margin-bottom: 10px">{{ message }}</p>
                        {% endfor %}
                        <input class="button is-primary is-medium" type="submit" value="立即注册">
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}